/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-109226-g2ad199ae31-20221125"
#endif /* AVUTIL_FFVERSION_H */
